name: eden
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - numpy
  - pyyaml
  - pandas
  - geopandas
  - ipykernel
  - pytest
  - rasterio
  - pyarrow
  - fastparquet
prefix: /Users/olivelo/opt/miniconda3/envs/eden
